// Regenerates src/iso_tables.rs from Foundation, the same source Apple documents for
// $(region) and $(lang).  Run on macOS:  swift scripts/generate_iso_tables.swift > src/iso_tables.rs
import Foundation

func emit(_ name: String, _ values: [String]) {
    let sorted = values.sorted()
    let lengths = Array(Set(sorted.map { $0.count })).sorted()
    print("/// Alternatives for the predefined variable, sorted for binary search.")
    print("pub(crate) static \(name): &[&str] = &[")
    for chunk in stride(from: 0, to: sorted.count, by: 12) {
        let slice = sorted[chunk..<min(chunk + 12, sorted.count)]
        print("    " + slice.map { "\"\($0)\"" }.joined(separator: ", ") + ",")
    }
    print("];")
    let lowered = sorted.map { $0.lowercased() }.sorted()
    print("/// The same alternatives, lowercased and re-sorted, for case-insensitive lookup.")
    print("pub(crate) static \(name)_LOWER: &[&str] = &[")
    for chunk in stride(from: 0, to: lowered.count, by: 12) {
        let slice = lowered[chunk..<min(chunk + 12, lowered.count)]
        print("    " + slice.map { "\"\($0)\"" }.joined(separator: ", ") + ",")
    }
    print("];")
    print("/// Distinct alternative lengths, in characters.")
    print("pub(crate) static \(name)_LENGTHS: &[usize] = &[\(lengths.map(String.init).joined(separator: ", "))];")
    print("")
}

let version = ProcessInfo.processInfo.operatingSystemVersion
print("//! ISO region and language tables backing the predefined `$(region)` and `$(lang)`")
print("//! substitution variables.")
print("//!")
print("//! Generated by `scripts/generate_iso_tables.swift` from Foundation's `Locale.isoRegionCodes`")
print("//! and `Locale.isoLanguageCodes` — the lists Apple's documentation points at.")
print("//!")
print("//! Source: macOS \(version.majorVersion).\(version.minorVersion).\(version.patchVersion)")
print("//! Do not edit by hand; rerun the generator instead.")
print("")
print("/// The Foundation release these tables were captured from.")
print("pub(crate) const SOURCE: &str = \"macOS \(version.majorVersion).\(version.minorVersion).\(version.patchVersion) Foundation\";")
print("")
emit("REGIONS", Locale.isoRegionCodes)
emit("LANGS", Locale.isoLanguageCodes)
